# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: ceph-controller
  type: group
  role: [ceph-controller]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, fuel_pkgs, globals, tools, logging,
    netconfig, hosts, firewall]  
  parameters:
    strategy:
      type: parallel

# - id: ceph-controller-deployment-puppet
#   type: puppet
#   groups: [ceph-controller]
#   required_for: [deploy_end]
#   requires: [deploy_start]
#   parameters:
#     puppet_manifest: "deploy.pp"
#     puppet_modules: "."
#     timeout: 3600

#- id: ceph-controller-post-deployment-sh
#  type: shell
#  role: [ceph-controller]
#  required_for: [post_deployment_end]
#  requires: [post_deployment_start]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: ceph-controller-pre-deployment-sh
#  type: shell
#  role: [ceph-controller]
#  required_for: [pre_deployment_end]
#  requires: [pre_deployment_start]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
